// Vite entry points generated by electron-forge
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;
declare const PREFERENCES_WINDOW_VITE_DEV_SERVER_URL: string;
declare const PREFERENCES_WINDOW_VITE_NAME: string;
