import { app, BrowserWindow, ipcMain, Menu, screen, Display } from "electron";
import { updateElectronApp } from "update-electron-app";
import settings from './settings';
import oscListener from "./osc";

import {
  add,
  differenceInMilliseconds,
  isPast,
  parse,
} from "date-fns";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const isMac = process.platform === "darwin";
const isDebug = process.env.NODE_ENV === "development";
const appSettings = new settings();
let mainWindow: BrowserWindow | null = null;
let timer: NodeJS.Timeout;

const getDisplayOrigin = (display: Display) => {
  if (display.bounds) {
    return { x: display.bounds.x, y: display.bounds.y };
  }

  const nativeOrigin = (display as any).nativeOrigin;
  return {
    x: nativeOrigin?.x || 0,
    y: nativeOrigin?.y || 0,
  };
};

const moveWindowToPreferredDisplay = (window: BrowserWindow, prefs: any) => {
  if (!window || window.isDestroyed()) {
    return;
  }

  const targetDisplayId = prefs.value("application.display");
  const displays = screen.getAllDisplays();
  const targetDisplay =
    displays.find(
      (display) => display.id.toString() === String(targetDisplayId)
    ) || screen.getPrimaryDisplay();

  if (!targetDisplay) {
    return;
  }

  const { width, height } = window.getBounds();
  const { x, y } = getDisplayOrigin(targetDisplay);
  window.setBounds({ x, y, width, height }, false);

  const shouldBeFullscreen = !!prefs.value("application.fullscreen");
  if (window.isFullScreen() !== shouldBeFullscreen) {
    window.setFullScreen(shouldBeFullscreen);
  }
};

const registerDisplayChangeHandlers = (window: BrowserWindow, prefs: any) => {
  const reposition = () => moveWindowToPreferredDisplay(window, prefs);

  screen.on("display-added", reposition);
  screen.on("display-removed", reposition);
  screen.on("display-metrics-changed", reposition);

  window.on("closed", () => {
    screen.removeListener("display-added", reposition);
    screen.removeListener("display-removed", reposition);
    screen.removeListener("display-metrics-changed", reposition);
  });
};

const createWindow = (): void => {
  const prefs = appSettings.prefs();

  const osc = new oscListener(appSettings.prefs);

  // Create the browser window.
  mainWindow = new BrowserWindow({
    x: 0,
    y: 0,
    fullscreen: false,
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    autoHideMenuBar: true,
  });

  moveWindowToPreferredDisplay(mainWindow, prefs);
  registerDisplayChangeHandlers(mainWindow, prefs);

  ipcMain.on("display:reset", () => {
    mainWindow?.webContents.send("display:reset");
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.on("closed", () => {
    clearInterval(timer);
    timer = null;
    mainWindow = null;
  });

  // Open the DevTools.
  if (isDebug && mainWindow) {
    mainWindow.webContents.openDevTools();
  }

  const menu = Menu.buildFromTemplate([
    {
      label: "File",
      submenu: [
        {
          label: "Preferences",
          click: () => {
            appSettings.show();
          },
        },
        isMac ? { role: "close" } : { role: "quit" },
      ],
    },
    {
      label: "View",
      submenu: [
        { role: "reload" },
        { role: "forceReload" },
        { role: "toggleDevTools" },
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "togglefullscreen" },
      ],
    },
  ]);

  Menu.setApplicationMenu(menu);

  timer = setInterval(() => {
    mainWindow?.webContents.send("timers:update", {
      currentTime: osc.currentTime,
      totalTime: osc.totalTime,
      remainingTime: osc.remainingTime,
      loop: osc.loop,
      stopped: osc.stopped,
      enableProductionClock: prefs.value("production.enable"),
      enableOntime: prefs.value("production.ontime"),
      ontimeCurrent: osc.ontimeCurrent,
      elapsedColor: prefs.value("colors.elapsed"),
      remainingColor: prefs.value("colors.remaining"),
      clockColor: prefs.value("colors.clock"),
      productionColor: prefs.value("colors.production"),
      startTime: prefs.value("production.start"),
      runtime: runtimeClock(
        prefs.value("production.start"),
        prefs.value("production.runtime")
      ),
    });
  }, 200);
};

const runtimeClock = (startTime: string, runtime: string) => {

  if (!startTime || !runtime) {
    return "00:00:00";
  }

  const timeFormat = /^(\d{2}:\d{2}:\d{2})$/;

  if (!timeFormat.test(startTime) || !timeFormat.test(runtime)) {
    return "00:00:00";
  }

  const runtimeDate = parse(runtime, "HH:mm:ss", new Date());
  const startDate = parse(startTime, "HH:mm:ss", new Date());
  const endDate = add(startDate, {
    hours: runtimeDate.getHours(),
    minutes: runtimeDate.getMinutes(),
    seconds: runtimeDate.getSeconds(),
  });

  if (isPast(startDate)) {
    const diff = differenceInMilliseconds(endDate, new Date());
    return new Date(diff).toISOString().substr(11, 8);
  } else {
    const diff = differenceInMilliseconds(startDate, new Date());

    return new Date(diff).toISOString().substr(11, 8);
  }
};

updateElectronApp();

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
